### ISSUE TITLE
No tab suggestions in Jupyter Lab console/notebook

### ISSUE THREAD

**Issue by narfanar** [evhub/coconut#469] opened 2018-12-26 09:30 UTC
Coconut kernels in the latest Jupyter Lab (console and notebook) do not show any suggestions on tab press. Proper Python works fine.

What logs/configs should I bring to you here?

**Comment by hoishing** [comment] 2019-01-17 11:12
same here, losing code completion in jupyter does affect productivity / usability... hope it can be fixed soon 🙏

**Comment by hoishing** [comment] 2019-01-17 17:46
Just found a work-around about it. Seems the code completion problem is caused by the jupyter-console module not supporting prompt-toolkit 2.0 yet. So downgrading prompt-toolkit to 1.0.15 could help.

If you use conda to install the packages, you may downgrade it by:

`conda install prompt_toolkit=1.0.15`

3 packages will be downgraded together

`ipython:         7.2.0-py36h39e3cac_0 --> 6.5.0-py36_0`
`jupyter_console: 6.0.0-py36_0         --> 5.2.0-py36_1`
`prompt_toolkit:  2.0.7-py36_0         --> 1.0.15-py36haeda067_0`

then restart jupyter and the code completion is back 🎉

**Comment by narfanar** [comment] 2019-01-17 18:30
> Just found a work-around about it. Seems the code completion problem is caused by the jupyter-console module not supporting prompt-toolkit 2.0 yet. So downgrading prompt-toolkit to 1.0.15 could help.
> 
> If you use conda to install the packages, you may downgrade it by:
> 
> `conda install prompt_toolkit=1.0.15`
> 
> 3 packages will be downgraded together
> 
> `ipython: 7.2.0-py36h39e3cac_0 --> 6.5.0-py36_0`
> `jupyter_console: 6.0.0-py36_0 --> 5.2.0-py36_1`
> `prompt_toolkit: 2.0.7-py36_0 --> 1.0.15-py36haeda067_0`
> 
> then restart jupyter and the code completion is back 🎉

According to https://github.com/jupyter/jupyter_console/issues/158 , it should actually be fixed with the combination you had at first, so this very weird.

**Comment by evhub** [comment] 2019-04-16 23:14
@narfanar @hoishing This should now be fixed on `coconut-develop`. Just `pip install -U coconut-develop` to get the latest version.

**Closed by evhub** 2019-04-16 23:14 UTC
Labels: oversight, resolved
