### ISSUE TITLE
Reimplement Coconut using Coconut

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#374] opened 2017-12-06 20:57 UTC
Could lead to improvements and probably even speedups and raises development to a new level.

**Comment by evhub** [comment] 2017-12-07 00:00
Duplicate of #110. It's unlikely that this would actually improve performance at all, since all of the optimizations that Coconut does automatically I've done to the codebase manually. My thinking is that this is probably more work than it's worth, though I'm not entirely opposed to it.

**Comment by ArneBachmann** [comment] 2017-12-07 12:16
Maybe in Coconut you could write "more functional" code that performs better :-)

**Closed** 2021-06-26 23:49 UTC
Labels: cleanup, won't fix
