### ISSUE TITLE
Mypy error in coconut header

### ISSUE THREAD

**Issue by tom-a-horrocks** [evhub/coconut#652] opened 2022-03-03 03:38 UTC
First, thanks for developing this package.

I'm unable to use mypy as there's a typing error in the header of the compiled file. This happens even for empty .coco files. To reproduce, create an empty coconut file and compile with `coconut empty_file.coco --strict --target 3.9 --mypy`, which should give the error:
```
c:\<redacted>\mypy_test.py:13: error: Value of type variable "AnyStr" of "dirname" cannot be "Optional[str]"
    if _coconut_cached_module is not None and _coconut_os.path.dirname(_coconut_cached_module.__file__) != _coconut_file_dir:
                                              ^
Found 1 error in 1 file (checked 1 source file)
Exiting with error: MyPy error
```
When running mypy directly on the compiled file via `mypy empty_file.py` there are more errors:
```
mypy_test.py:13: error: Value of type variable "AnyStr" of "dirname" cannot be "Optional[str]"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_tail_call"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_tco"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_MatchError"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_igetitem"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_base_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_forward_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_back_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_forward_star_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_back_star_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_forward_dubstar_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_back_dubstar_compose"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_star_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_dubstar_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_back_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_back_star_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_back_dubstar_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_none_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_none_star_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_none_dubstar_pipe"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_bool_and"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_bool_or"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_none_coalesce"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_minus"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_map"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_partial"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_get_function_match_error"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_base_pattern_func"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_addpattern"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_sentinel"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_assert"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_mark_as_match"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_reiterable"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_self_match_types"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_dict_merge"
mypy_test.py:31: error: Module "__coconut__" has no attribute "_coconut_exec"
Found 38 errors in 1 file (checked 1 source file)
```

This is for Version 1.6.0 [Vocational Guidance Counsellor] running on Python 3.9.7 and Cython cPyparsing v2.4.7.1.1.0.

**Comment by tom-a-horrocks** [comment] 2022-03-03 05:36
This was actually two separate issues.

**Issue 1: error during `coconut empty_file.coco --strict --target 3.9 --mypy`**
This does not occur in the development version, so I'm guessing this will be fixed in the next release. Perhaps you can recommend a stable commit to use in the meantime? 

For anyone else impacted by this, you can try switching to the development branch by running:
```
pip uninstall coconut
pip install coconut-develop
```
See https://coconut.readthedocs.io/en/latest/DOCS.html#develop-version for more instructions.

**Issue 2: many errors during `mypy empty_file.py`**
Mypy could not find my coconut stubs file. Step-by-step to fix:
1. Run `coconut --mypy install` and copy the reported stubs location.
2. Create the mypy configuration file `mypy.ini` containing the stubs location. On my Windows machine, my config file looks like:
```
[mypy]
mypy_path = c:\\Users\\<myusername>\\.coconut_stubs
```
3. Point mypy to your configuration file when you run it, e.g. `mypy empty_file.py --config mypy.ini`.

**Comment by evhub** [comment] 2022-03-03 08:02
This was caused by a `mypy` update after Coconut `1.6.0`'s release that invalidated the stub file shipped with that version, so another solution should be to backdate your `mypy` by installing `mypy` using `pip install coconut[mypy]`.

As you already noted, it should be fixed with the latest mypy if you install `coconut-develop`. As for what commit to use—the `coconut-develop` PyPI package is only updated when a commit passes tests, so it should be fine to just use the latest version on that package.

As for the issues with running `mypy` directly, what you're suggesting is indeed valid—you can also add `~/.coconut_stubs` to your `MYPYPATH` as the [documentation recommends](https://coconut.readthedocs.io/en/latest/DOCS.html#mypy-integration).

**Closed by evhub** 2022-03-03 08:02 UTC
Labels: bug, resolved
