### ISSUE TITLE
Improve installation instructions. Mention PATH.

### ISSUE THREAD

**Issue by baryluk** [evhub/coconut#211] opened 2017-01-26 02:10 UTC
Hi,

I use Python for almost 10 years, but really I am a noob about pip.

I followed instructions on coconut-lang.org and http://coconut.readthedocs.io/en/master/HELP.html and dist-info / PIP metadata.

So, I executed pip install coconut, on my Debian Linux sid machine. With a bit of python already installed from Debian. That parts worked fine, with downloading dependencies and unpacking it somewhere in .local.

And tried executing coconut -h / coconust as explained in the tutorial. But it is not in the PATH.

$  pip show coconut
Name: coconut
Version: 1.2.0
Summary: Simple, elegant, Pythonic functional programming.
Home-page: http://coconut-lang.org
Author: Evan Hubinger
Author-email: evanjhub@gmail.com
License: UNKNOWN
Location: /home/baryluk/.local/lib/python2.7/site-packages
Requires: pyparsing, prompt-toolkit, pygments

I guess, I need to add ~/.local/bin to my PATH? That is not obvious at all, and almost no distribution default .profile / .bashrc adds this to the PATH by default. (I keep personal scripts in ~/bin for example).

Please update mentioned 3-4 pages about that.

Thanks.

**Comment by evhub** [comment] 2017-01-26 03:21
@baryluk `pip` automatically installs Coconut's command-line scripts to wherever the script directory is for the Python installation that `pip` is running off of. When you install Python, that directory should be added to your `PATH`. If that directory isn't in your path, then your installation of Python is somehow faulty. The simple fix is just do what you did and add whatever directory is being used to your `PATH`, but the better solution is to [download and install a full Python distribution from `python.org`](https://www.python.org/downloads/) so that you no longer have a faulty Python installation. The tutorial already has "install Python" as its first step in the installation section, with the same link I gave above, although I could probably be more specific about the need to install it _from that link_ instead of just using whatever installation might come with your OS (which are often old, faulty installations).

**Comment by baryluk** [comment] 2017-01-26 23:23
Why anybody would want to install Python directly from python.org, if one is provided in their repositories with secure, easy and automatic updates of Python and multiple other Python packages?

Not to mention that python.org/downloads doesn't provide any prebuilt binaries of Python for Linux for any architecture. That means users need to download sources, verify them, unpack, install all the dependencies (the C compiler for the start), compile it, possibly run tests, and then install it. It can take hours easily.

Is there any Linux distribution that supposedly set PATH in a way that installing coconut via pip install coconut (under normal user), make it work out of the box?

Excuse me, but saying that my Python is faulty or old is silly (I have 2.7.13 and 3.5.3  installed, which are the same as version as the most up to date official versions that was released this in last month and LAST WEEK respectively). It is perfectly valid installation of Python, and probably more than 80% of all Python installations are like mine, with Python coming from distro package manager (Debian, Ubuntu, Mint, CentOS, Fedora, Arch, Gentoo, you name it). And probably more than 95% of all Linux users and Python developers.

In fact I am certain that even installing Python using files from python.org/download, will not solve this problem. To test that, I created a recent Ubuntu docker container, 'docker -t -i ubuntu /bin/bash', done apt-get install wget xz-utils build-essential, created a new user, and then download the Python source, uncompressed it, run ./configure, then make -j20 (this part took around 25 minutes on my high end machine) to build and test everything, then sudo make install (another 30 minutes, because it build some more stuff for some reasons). Then I needed to redo everything because apparanetly PIP is not installed by default in Python! So, ./configure --with-ensurepip && make clean && make -j20 && sudo make install, and wait another 45 minutes or so. If one wants the PGO / FDO, as is usually done by the distros, you need to pass --enable-optimizations, and wait another hour or so profiling and recompiling twice. It can take entire day on a slow machine.

And then it ends with an error:

    zipimport.ZipImportError: can't decompress data; zlib not available.

So then you find out, that more dependencies are missing for the pip to work correctly. So, you go to thing like http://bazaar.launchpad.net/~doko/python/pkg2.7-debian/view/head:/control and install most of the interesting build dependencies, that most likely will be required in any normal Python installation:

    apt-get install zlib1g-dev libbz2-dev libsqlite3-dev libreadline-dev libtinfo-dev libffi-dev  libgdbm-dev libssl-dev sharutils

And repeat:

    ./configure --with-ensurepip (--enable-optimizations if you are brave too, as the compilation with FDO / PGO is about 3-4 times slower) && make -j20 && sudo make install

Then you find out it ends with an error too:

    Python build finished, but the necessary bits to build these modules were not found:
    _bsddb             _curses            _curses_panel   
    _tkinter           bsddb185           dl              
    imageop            sunaudiodev          

But anyway, you ignore it, and do sudo make install. And voila, the python2.7 and pip are available in PATH, as they are in /usr/local/bin. Ok, good.

You check your PATH:
    
    $ env | grep PATH
    PATH=/home/wb/bin:/home/wb/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

and it looks promising.

Where it is coming from?  It is not in ~/.bashrc or in /etc/profile, or in /etc/environment, or in /etc/pam*, or in /etc/login.defs.  But you eventually find it is in /etc/skel/.profile, and indeed is also in ~/.profile:

    $ tail -2 ~/.profile 
    # set PATH so it includes user's private bin directories
    PATH="$HOME/bin:$HOME/.local/bin:$PATH"
    $

And this part, actually have ZERO to do with Python, or the fact that I installed python from python.org. It just happens that Ubuntu is shipping with different /etc/skel/.profile than upstream from Debian.

The one in Debian (testing/unstable), is to this day like this:

    $ tail -4 /etc/skel/.profile 
    # set PATH so it includes user's private bin if it exists
    if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
    fi
    $
    $ env | grep PATH
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    $


This file is coming from bash 4.4-4 package in Debian. Interestingly the version in Ubuntu, is older 4.3-14ubuntu1.1. They just tweak the .profile file.

It means, that actually performing same (few hours) build on my Debian machine (instead in docker), would end in exactly same issue.

My personal PATH, was PATH=/home/baryluk/bin:/home/baryluk/go/bin:/home/baryluk/youtube-dl:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games, which also doesn't include ~/.local/bin, because I never (in 15 years of using Linux), have any case of needing it. (Of course I added it now just for coconut).

On that a bit more later. Lets try if the pip works actuall.

    $ pip install coconut
    Collecting coconut
      Downloading coconut-1.2.0-py2.py3-none-any.whl (63kB)
        100% |################################| 71kB 1.4MB/s 
    Collecting pyparsing==2.1.9 (from coconut)
      Downloading pyparsing-2.1.9-py2.py3-none-any.whl (55kB)
        100% |################################| 61kB 9.4MB/s 
    Collecting prompt-toolkit==1.0.7 (from coconut)
      Downloading prompt_toolkit-1.0.7-py2-none-any.whl (237kB)
        100% |################################| 245kB 4.5MB/s 
    Collecting pygments==2.1.3 (from coconut)
      Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
        100% |################################| 757kB 2.3MB/s 
    Collecting six>=1.9.0 (from prompt-toolkit==1.0.7->coconut)
      Downloading six-1.10.0-py2.py3-none-any.whl
    Collecting wcwidth (from prompt-toolkit==1.0.7->coconut)
      Downloading wcwidth-0.1.7-py2.py3-none-any.whl
    Installing collected packages: pyparsing, six, wcwidth, prompt-toolkit, pygments, coconut
    Exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
        prefix=options.prefix_path,
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
        clobber(source, lib_dir, True)
      File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
        shutil.copyfile(srcfile, destfile)
      File "/usr/local/lib/python2.7/shutil.py", line 83, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/pyparsing.pyc'
    $

Yeah. It doesn't. So, maybe pass some option that isn't really mentioned on the first page of pip help? You go to https://pip.pypa.io/en/stable/reference/pip_install/#options, and find out there is --user option, which for some reason, is disabled by default on this fresh install of python in Ubuntu (and no, there is other python around: `dpkg -l | grep python` is EMPTY) with default options. Which for some reasons is different than what you would get installing python from Ubuntu or Debian packages in the first place.

Ok, anyway. Retry:

    $ pip install coconut --user
    Collecting coconut
      Using cached coconut-1.2.0-py2.py3-none-any.whl
    Collecting pyparsing==2.1.9 (from coconut)
      Using cached pyparsing-2.1.9-py2.py3-none-any.whl
    Collecting prompt-toolkit==1.0.7 (from coconut)
      Using cached prompt_toolkit-1.0.7-py2-none-any.whl
    Collecting pygments==2.1.3 (from coconut)
      Using cached Pygments-2.1.3-py2.py3-none-any.whl
    Collecting six>=1.9.0 (from prompt-toolkit==1.0.7->coconut)
      Using cached six-1.10.0-py2.py3-none-any.whl
    Collecting wcwidth (from prompt-toolkit==1.0.7->coconut)
      Using cached wcwidth-0.1.7-py2.py3-none-any.whl
    Installing collected packages: pyparsing, six, wcwidth, prompt-toolkit, pygments, coconut
    Successfully installed coconut-1.2.0 prompt-toolkit-1.0.7 pygments-2.1.3 pyparsing-2.1.9 six-1.10.0 wcwidth-0.1.7
    $

That is promising.

    $ coconut
    Coconut Interpreter:
    (type "exit()" or press Ctrl-D to end)
    >>> 

Ok, so it kind of works on Ubuntu at least.

Lets try the same on Debian:

    $ docker run -t -i debian:unstable /bin/bash
    docker# apt-get update && apt-get install wget xz-utils build-essential less zlib1g-dev libbz2-dev libsqlite3-dev libreadline-dev libtinfo-dev libffi-dev  libgdbm-dev libssl-dev sharutils -y
    docker# adduser baryluk
    docker# su - baryluk
    docker$ wget -q https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
    docker$ tar xf Python-2.7.13.tar.xz
    docker$ cd Python-2.7.13
    docker$ ./configure --with-ensurepip
    docker$ time make -j12
    docker$ exit
    docker# cd /home/baryluk/Python-2.7.13
    docker# time make install -j12
    docker$ su - baryluk
    docker$ python --version
    Python 2.7.13
    docker$ dpkg -l | grep python
    docker$ pip --version
    pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
    docker$ pip install coconut --user
    ....
    docker$ coconut
    -su: coconut: command not found
    docker$

Nope.

It can take easily more than one hour on older machines (without plenty of memory, fast disk and fast CPU) to install Python this way. And in the end, it would still not work on Debian and presumably many other Linux distributions, that do not add ~/.local/bin PATH in .profile or somewhere else by default. (The question to make Debian add ~/.local/bin by default to the PATH, is really outside of the scope of this bug, and definitively is not going to be solved quickly. In fact I am pretty sure there might be an opposition for doing this for a root user due to the security reasons).

And if somebody doesn't have access to the root, maybe on some shared machine or a secure container, they are going to have very bad day. Downloading all the dependencies (and their dependencies) manually, setting --prefix, and at the end of the day ending setting PATH to custom location anyway!

Please mention PATH issue in the instructions. It is going to be much easy to use by people and as I already said, that is the only thing required to fix it. Or alternatively suggest to run 'pip install coconut' from root, to install it system wide, presumably in /usr/local/bin/:

    # sudo pip install coconut
    # /usr/local/bin/coconut --version
    Version 1.2.0 [Colonel] running on Python 2.7.13 (default, Jan 26 2017,
    23:10:02) [GCC 6.3.0 20170124]
    #
    $ coconut
    Coconut Interpreter:
    (type "exit()" or press Ctrl-D to end)
    >>> 

Can I ask which OS are you using on your personal machine used for the development of coconut?

**Comment by evhub** [comment] 2017-01-27 06:00
> Excuse me, but saying that my Python is faulty or old is silly (I have 2.7.13 and 3.5.3 installed, which are the same as version as the most up to date official versions that was released this in last month and LAST WEEK respectively). It is perfectly valid installation of Python, and probably more than 80% of all Python installations are like mine, with Python coming from distro package manager (Debian, Ubuntu, Mint, CentOS, Fedora, Arch, Gentoo, you name it). And probably more than 95% of all Linux users and Python developers.

@baryluk I probably should have been more clear about that, sorry! The problem isn't the version of Python, nor the files that are being installed themselves, but, like you said, whether `PATH` is getting set at some point. Using a package manager should be fine. I know `apt` works fine on my Ubuntu box, for example. The problem, though, is while that works in some cases, it doesn't necessarily work in all cases--that's why I recommended just reinstalling Python in a way I knew would be correct. It's great that you were able to fix your problem just with `sudo` or `--user`--I didn't expect it was a permissions problem, but that's definitely something I'll add to the tutorial!

Thanks for putting so much effort into giving me all of that information in the issue--I appreciate it!

**Comment by evhub** [comment] 2017-01-27 18:55
Resolved with #212.

**Closed by evhub** 2017-01-27 18:55 UTC
Labels: compatibility, documentation
