### ISSUE TITLE
Coconut Jupyter kernel trying to install into a hard-coded directory

### ISSUE THREAD

**Issue by petrilli** [evhub/coconut#277] opened 2017-06-27 04:28 UTC
This may be related to issue #97, but I get this when attempting to run inside a virtualenv:

```
$ coconut --verbose --jupyter
Command args: Namespace(code=None, dest=None, display=False, documentation=False, force=False, interact=False, jobs=None, jupyter=[], keep_lines=False, line_numbers=False, minify=False, mypy=None, no_tco=False, no_write=False, package=False, quiet=False, recursion_limit=None, run=False, source=None, standalone=False, strict=False, style=None, target=None, tutorial=False, verbose=True, watch=False)
Compiler args: {'no_tco': False, 'keep_lines': False, 'line_numbers': False, 'minify': False, 'strict': False, 'target': ''}
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter --version
4.3.0
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter kernelspec install /Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/coconut/icoconut/coconut --replace
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter kernelspec install /Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/coconut/icoconut/coconut --replace --user
[InstallKernelSpec] Removing existing kernelspec in /Users/petrilli/Library/Jupyter/kernels/coconut
[InstallKernelSpec] Installed kernelspec coconut in /Users/petrilli/Library/Jupyter/kernels/coconut
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter kernelspec install /Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/coconut/icoconut/coconut2 --replace
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter kernelspec install /Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/coconut/icoconut/coconut2 --replace --user
[InstallKernelSpec] Removing existing kernelspec in /Users/petrilli/Library/Jupyter/kernels/coconut2
[InstallKernelSpec] Installed kernelspec coconut2 in /Users/petrilli/Library/Jupyter/kernels/coconut2
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter kernelspec install /Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/coconut/icoconut/coconut3 --replace
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
> /Users/petrilli/.virtualenvs/coconut/bin/jupyter kernelspec install /Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/coconut/icoconut/coconut3 --replace --user
[InstallKernelSpec] Removing existing kernelspec in /Users/petrilli/Library/Jupyter/kernels/coconut3
[InstallKernelSpec] Installed kernelspec coconut3 in /Users/petrilli/Library/Jupyter/kernels/coconut3
```

This is with:

```
jupyter==1.0.0
coconut==1.2.3
ipython==5.3.0
```

I've tried digging into it, and it seems like the kernel is partially installed?

```
$ jupyter console --kernel=coconut3
Jupyter console 5.1.0

Coconut 1.2.3 [Colonel]


In [1]: "Hello world" |> print
/Users/petrilli/.virtualenvs/coconut/lib/python3.6/site-packages/jupyter_console/ptshell.py:599: User. warn('The kernel did not respond to an is_complete_request. '
In [1]: "Hello world" |> print
Hello world
```

**Comment by evhub** [comment] 2017-06-27 05:36
@petrilli Thanks for the issue! Your kernel installation did succeed; the error you're seeing is just because installing globally failed, so it installed locally instead. I should probably make it so that error is only actually shown if you pass `--verbose`, since that error should never actually be an issue. However, the `'The kernel did not respond to an is_complete_request. '` error you're seeing does look to be some sort of bug with the kernel. I'll try to reproduce that one and see what I can do about it.

**Comment by evhub** [comment] 2017-06-28 06:59
@petrilli This should be fixed on `develop`! Just `pip install coconut-develop` to test out the new version.

**Closed by evhub** 2017-06-28 06:59 UTC
Labels: bug
