### ISSUE TITLE
Wrong f-string parsing and compile warning

### ISSUE THREAD

**Issue by shilkazx** [evhub/coconut#840] opened 2024-06-06 09:14 UTC
coconut v3.1.0 with python v3.9.18
coconut can not parse multi-line f-string properly. It will remove 'f' before the multi-line string and the compiled code is wrong.
e.g.
coconut code:
```
sql = f'''SELECT * 
                FROM SOME_TABLE
                WHERE CODE = '{self.code}' '''
```
compile this code would raise warning:
**CoconutSyntaxWarning: f-string with no expressions (line xxx in 'xxx.coco')**
and the compiled code is:
```
sql = '''SELECT * 
                FROM SOME_TABLE
                WHERE CODE = '{self.code}' '''.format()
```
This code is totally wrong. Coconut should just copy the original code snippet in the generated python file.

**Comment by evhub** [comment] 2024-06-06 19:32
Looks like a duplicate of #839, which should already be resolved on `coconut-develop`. Try `pip uninstall coconut && pip install -U coconut-develop`.

**Closed by evhub** 2024-06-06 19:32 UTC
Labels: bug, duplicate
