### ISSUE TITLE
Coconut kernel when used in Jupyter lab/notebook has trouble parsing comments

### ISSUE THREAD

**Issue by Abrackadabra** [evhub/coconut#852] opened 2024-08-25 00:30 UTC
Min repro:

```bash
$ poetry init
...
$ poetry add jupyterlab coconut
...
$ poetry run coconut --jupyter lab
...
```

In jupyter do
```
[
  #
]
```

<img width="472" alt="image" src="https://github.com/user-attachments/assets/223da58f-c2f1-481b-9c63-8ca3d9367555">

This is somehow lab/notebook specific, just running the kernel in ipython is okay.

**Comment by evhub** [comment] 2024-08-25 01:12
Duplicate of #851. It's fixed on `coconut-develop`, but I'll try to get out a hotfix release to fix it on the release branch as well as soon as I can.

**Closed by evhub** 2024-08-25 01:12 UTC
Labels: bug, duplicate
