### ISSUE TITLE
Assignment functions with compound statement

### ISSUE THREAD

**Issue by MatthiasJ1** [evhub/coconut#832] opened 2024-03-04 21:25 UTC
Assignment functions whose last statement is a compound statement should return the value of the final expression of the active code path.

```py
def f(x)=
    if x:
        # some code
        x+1
    else: 0

def f(x)=
    match x:
        case 0: -1
        case _: x

def f(x)=
    with open(x, "r"):
        x.read()
```

Compiles to (3.10):
```py
def f(x):
    if x:
        # some code
        return x+1
    else:
        return 0

def f(x):
    match x:
        case 0: return -1
        case _: return x

def f(x):
    with open(x, "r"):
        return x.read()
```

**Comment by evhub** [comment] 2024-03-05 05:53
Closing as duplicate of #190.

**Closed by evhub** 2024-03-05 05:53 UTC
Labels: modification, duplicate
