### ISSUE TITLE
np.loadtxt ValueError fname must be a string, file handle, or generator

### ISSUE THREAD

**Issue by shizhaojingszj** [evhub/coconut#447] opened 2018-10-11 05:57 UTC
pyenv 2.7.12
numpy==1.14.5
Coconut: Version 1.4.0 [Ernest Scribbler] running on Python 2.7.12

mini fail demo
===============
import numpy as np

xy = np.loadtxt("somefile", delimiter=",", dtype=np.float32)  # line 6

error
===========

File ".../venv2.7.12/lib/python2.7/site-packages/numpy/lib/npyio.py", line 925, in loadtxt
    raise ValueError('fname must be a string, file handle, or generator')
ValueError: fname must be a string, file handle, or generator

description
==============
mini fail shows everything, can anybody reproduce this?

**Comment by evhub** [comment] 2018-10-11 20:30
Your example works for me under Python `2.7.13` and numpy `1.14.5`. Just to test a hypothesis, if you try
```
xy = np.loadtxt(b"somefile", delimiter=b",", dtype=np.float32)
```
instead, does it work?

**Comment by shizhaojingszj** [comment] 2018-10-12 04:11
Yes, after changing to binary string, the above error goes away.

**Comment by evhub** [comment] 2019-03-03 10:54
@shizhaojingszj I'm not sure why it works for me and not for you, but I'm closing this as a won't fix--by design Coconut always uses unicode literals. If you need bytes instead (e.g. for compatibility reasons), my recommendation is to use `py_str`.

**Closed by evhub** 2019-03-03 10:54 UTC
Labels: compatibility, won't fix

**Comment by shizhaojingszj** [comment] 2019-03-04 11:12
ok now cas we have ported to py36
