### ISSUE TITLE
Document None checks

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#420] opened 2018-04-01 12:00 UTC
We discussed and dismissed a similar idea some time ago...
What about: `if value?: <suite>` instead of `if value is not None: <suite>` to avoid cases were value would evaluate to False even if not None?

It's just some characters, but fits the `??` logic well.

**Comment by auscompgeek** [comment] 2018-04-01 12:06
See also: https://www.python.org/dev/peps/pep-0505/

**Comment by evhub** [comment] 2018-04-01 22:46
Marking as duplicate of #368.

@ArneBachmann I think I still have the same opinion on this, which is that it's worth the extra characters here to make the code more explicit. Code is read more often than it's written, so the most important thing is making which is easy to read. I think `??` and `?.` make code easier to read beccause they turn what would otherwise be very complex short-circuiting expressions into a single operator. But with `value is None` or `value is not None`, that's literally just english, which means it's basically already as easy to read as possible. Changing `value is None` to `value?` imo makes it harder to understand what that code is doing, since it replaces an english expression with a symbol whose meaning you have to just learn.

@auscompgeek I think Coconut actually already implements all of PEP 505 (see #243). Do you know of anything in PEP 505 that we don't have?

**Comment by auscompgeek** [comment] 2018-04-02 01:19
The docs seem to suggest that the None-aware indexing operation in PEP 505 isn't implemented. (I'm not sure I like the syntax for it anyway.)

Would probably be a good idea to link to PEP 505 in the docs, I guess?

**Comment by evhub** [comment] 2018-04-02 03:33
@auscompgeek See:
> Coconut also allows a single ? before attribute access, function calling, partial application, and (iterator) indexing to short-circuit the rest of the evaluation if everything so far evaluates to None.

I like the idea of linking to PEP 505, and to be fair in addition to the above sentence I should probably also give an example of using None-aware indexing.

**Comment by ArneBachmann** [comment] 2018-04-03 10:37
OK, I understand the rationale. Looking forward to potential PEP 505 universal support, if coming.

**Comment by evhub** [comment] 2018-04-03 20:28
I'm not sure how to make this more clear, but Coconut _already has universal PEP 505 support._ Not only that, but Coconut supports lots of things PEP 505 doesn't support, such as:
```python
maybe_none = None
maybe_none?[0]
maybe_none?(arg)
maybe_none?$(arg)
maybe_none?$[0]
maybe_none?[]
maybe_none?.
```
Clearly if so many people are confused on this issue, I need to make the documentation better, so I'm leaving this issue open with the idea of adding all of the above to the documentation.

**Closed** 2018-10-13 07:12 UTC
Labels: documentation, feature, resolved
