### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by synth-me** [evhub/coconut#600] opened 2021-10-20 00:12 UTC
Do you have any logo in mind ? @evhub 
I design this one but it's just an random thought. I think a logo for coconut would be great ! 
![PicsArt_10-19-09 03 00](https://user-images.githubusercontent.com/68300901/138006963-df90f23d-b198-45d5-935b-f664d6edb642.png)
( If this issue already exists let me know )

**Comment by carloocchiena** [comment] 2021-11-24 21:28
Isn't this a duplicate of [Design a coconut logo?](https://github.com/evhub/coconut/issues/50#issuecomment-976823106)?
Anyway here's my submission! 

i followed a clean minimalist approach, with negative space. 

![image](https://user-images.githubusercontent.com/57464184/143314922-0aa53f1d-8b09-4c7b-a59e-33a8df1c05b4.png)

**Comment by synth-me** [comment] 2021-11-29 14:02
Well I think that's a pretty cool design and i think you designed a great symbol. I'd like to see the opinion of the core devs which can take the decision to merge the logo to the next doc's version .

**Comment by evhub** [comment] 2021-12-07 09:16
Thanks for all the suggestions! I've decided to adopt one of the submissions from #50, so I'm closing this issue now as a duplicate.

**Closed by evhub** 2021-12-07 09:16 UTC
Labels: duplicate, documentation
