### ISSUE TITLE
Let assignment functions return from any expression

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#341] opened 2017-10-22 21:29 UTC
Currently assignment function may `return value` in its code block, but allows `expression` instead of `return expression` in the last physical line of the function definition.

This is by no means functional, not even a convenience helper.
I think we discussed this before, but to be functional, we need a truely expression-like `if` or `case/match` construct (like in Erlang).

I imagine
```
if cond1:
  expr1
elif cond2:
  expr2
else:
  expr3
```
should be an expression that can be used as the last expression in an assignment function, allowing to remove the `return` statement in all branches.

**Comment by evhub** [comment] 2017-10-23 01:40
@ArneBachmann This is a duplicate of #190.

**Closed by evhub** 2017-10-23 01:40 UTC
