### ISSUE TITLE
Ipython and Jupyter aren't working

### ISSUE THREAD

**Issue by regr4** [evhub/coconut#551] opened 2020-09-01 20:25 UTC
Hi, I was trying to get Coconut to work with jupyter and ipython, but when I try to run anything, I get the following error message:

    ----------------------------------------------------------
    TypeError                Traceback (most recent call last)
    /usr/local/lib/python3.8/site-packages/IPython/core/async_helpers.py in _pseudo_sync_runner(coro)
     66     """
     67     try:
    ---> 68         coro.send(None)
     69     except StopIteration as exc:
     70         return exc.value

    /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/coroutines.py in coro(*args, **kw)
    122         @functools.wraps(func)
    123         def coro(*args, **kw):
    --> 124             res = func(*args, **kw)
    125             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    126                     isinstance(res, CoroWrapper)):

    TypeError: run_cell_async() got an unexpected keyword argument 'transformed_cell'

This happens in Jupyter notebooks, in Jupyterlab and in the ipython repl.

What I've tried so far:
- removing and reinstalling the `coconut` kernels
- uninstalling `coconut` and installing `coconut-develop`
- searching through the github issues for the same problem.

my OS is macOS Catalina, 10.15.6. I have python 3.8 installed via homebrew.

Is this something that has happened to more people? Is there a fix already or is this a new bug? 

Thanks for coconut though, it's a really cool language (and much less scary than something like Haskell (-; )

**Comment by evhub** [comment] 2020-09-01 21:21
@regr4 This looks like an IPython error to me, not a Coconut error. I would first try updating your IPython/Jupyter via `pip install --upgrade jupyter ipython ipykernel`, then if that doesn't work try raising an [IPython issue](https://github.com/ipython/ipython/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) rather than a Coconut issue.

**Comment by regr4** [comment] 2020-09-01 22:00
I've upgraded some jupyter stuff, but it doesn't seem to have helped. I'll raise an issue on the ipython github page later. 

jupyter --version outputs this:
`jupyter core     : 4.6.3`
`jupyter-notebook : 6.1.3`
`qtconsole        : 4.7.6`
`ipython          : 7.18.1`
`ipykernel        : 5.3.4`
`jupyter client   : 6.1.7`
`jupyter lab      : 2.2.6`
`nbconvert        : 5.6.1`
`ipywidgets       : 7.5.1`
`nbformat         : 5.0.7`
`traitlets        : 5.0.0`

**Comment by xxdavid** [comment] 2020-10-07 15:00
Hey, I had the same problem as you do (and also macOS Catalina, Python 3.8 from brew). For me, the issue was resolved by downgrading coconut to 1.4.0 (with `pip install --force-reinstall coconut==1.4.0`). I tried all the newer versions too (1.4.1, 1.4.2 and 1.4.3) but it seems it's broken since 1.4.1.

For record:
```
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.4
```

Thank you for making coconut! Tell me if there's anything I can do to fix this bug in newer versions.

**Comment by evhub** [comment] 2020-10-07 20:13
@xxdavid @regr4 I can't seem to replicate this error myself. Would either of you be able to provide more detailed instructions on how exactly you produced this error? What commands did you run, what was in your notebook/cell when you ran it, etc.

**Comment by regr4** [comment] 2020-10-07 21:14
I have run `pip3 install -U coconut-develop`. Still, when I ran `jupyter console --kernel=coconut` and entered `print("a")`, the error is the same as above. 
Also, if I run `jupyter lab` and open a coconut console, I also got the error.

**Comment by xxdavid** [comment] 2020-10-14 09:37
The same for me. I have run `pip uninstall coconut && pip install -U --user coconut-develop` and when I run `jupyter console --kernel=coconut` and enter anything (eg. just `1`) I get the error message mentioned in the first post. When I run `jupyter lab` and open console in Jupyter Lab with coconut kernel, I get the same error, if I open a notebook in coconut and run any cell there,  I get the same error again.

**Comment by ruivieira** [comment] 2020-10-27 08:50
I can confirm that this happens with coconut 1.43 on macOS 10.15.6 and Jupyter Lab 2.2.8 (`IPython.sys_info()` at the bottom) and that @xxdavid work-around also works (downgrading to coconut 1.4.0).



`IPython.sys_info()`:

```
"{'commit_hash': '95d2b79a2',
   'commit_source': 'installation',
   'default_encoding': 'utf-8',
   'ipython_path': '/Users/ruivieira/Library/Caches/pypoetry/virtualenvs/python-experiments-book-gQP3g2TK-py3.8/lib/python3.8/site-packages/IPython',
   'ipython_version': '7.18.1',
   'os_name': 'posix',
   'platform': 'macOS-10.15.6-x86_64-i386-64bit',
   'sys_executable': '/Users/ruivieira/Library/Caches/pypoetry/virtualenvs/python-experiments-book-gQP3g2TK-py3.8/bin/python',
   'sys_platform': 'darwin',
   'sys_version': '3.8.5 (default, Oct  8 2020, 11:52:34) [Clang 10.0.1 ]'
}"
```

**Comment by evhub** [comment] 2020-10-27 20:01
@bj0 Thank you for finding that! I believe the issue should now be fixed on `coconut-develop`. @regr4 @xxdavid @ruivieira Please let me know whether it works now if you `pip install -U coconut-develop>=1.4.3-post_dev54`.

**Comment by evhub** [comment] 2020-10-27 23:23
@bj0 Great! Closing this issue as resolved. The fix will go out in the next release.

**Closed by evhub** 2020-10-27 23:23 UTC
Labels: compatibility
