### ISSUE TITLE
Automatically return value of last expression in a function

### ISSUE THREAD

**Issue by chuckwondo** [evhub/coconut#143] opened 2016-08-10 16:58 UTC
Would it be possible to have the Coconut compiler automatically return the value of the last expression in a function?

Having to explicitly use the `return` keyword in front of the last expression of a function is not the end of the world, but it would be nice to be able to drop it, as is the case in a number of other functional languages.

I'd rank this in the same category as being able to drop the `lambda` keyword. Not a biggie, but it sure is convenient and keeps code (and typing) to a minimum (and thus, arguably, cleaner).

**Comment by evhub** [comment] 2016-08-10 18:02
Introducing automatic `return` into standard function definition would break compatibility with Python 3 code. If your function is only a single expression, however, [shorthand function notation](http://coconut.readthedocs.io/en/master/DOCS.html#shorthand-functions) should do what you want.

**Comment by chuckwondo** [comment] 2016-08-10 18:06
Yes, I like the shorthand function notation quite a bit! However, I was thinking about longer functions in this case. Would you elaborate on the breakage of the Python 3 compatibility?

**Comment by evhub** [comment] 2016-08-10 18:54
@chuckwondo Coconut guarantees that all valid Python 3 code is valid Coconut code. If functions were changed to automatically return their last expression, valid Python 3 code when compiled by Coconut would break.

**Comment by evhub** [comment] 2016-08-10 19:01
The only way in which something like this could be implemented is if it was only done in functions that were marked in some way. A possibility is to extend shorthand function notation so that
```
def some_func() =
    some_stmt
    some_expr
```
would compile to
```
def some_func():
    some_stmt
    return some_expr
```
since that wouldn't break Python code. I am against doing some like that, however, because it would mean that you wouldn't be able to tell whether the last expression was getting returned automatically or not without going all the way up to the function definition and checking whether it uses `=` or `:`.

Thus, I'm closing this issue until someone can come up with a good way to do this that neither breaks Python compatibility nor makes understanding what a function is doing more difficult.

**Comment by chuckwondo** [comment] 2016-08-10 19:23
@evhub I'm still confused as to how this would break Python 3 compatibility. Couldn't the Coconut compiler simply insert the `return` keyword in front of the last statement in a function if it's missing? How would that prevent all valid Python 3 code from being valid Coconut code?

**Comment by evhub** [comment] 2016-08-10 19:57
@chuckwondo On Python 3, you can do
```
def return_None:
    100
assert return_None() is None
```
but that would fail if `return_None` was automatically modified to return `100`. Although this example is unrealistic, lots of Python code does depend on functions returning `None` without an explicit `return` statement, and breaking that would be a huge compatibility issue.

**Comment by chuckwondo** [comment] 2016-08-10 20:17
@evhub Ah, thanks for the clarification. What if this were supported by a compiler flag? Perhaps under the `--strict` flag or some new flag? Alternatively, would you elaborate on the difficulty with extending the shorthand function notation, which I think might be a nice approach?

**Comment by evhub** [comment] 2016-08-10 21:20
@chuckwondo Compiler flags should never control actual features. If that was possible, then you would never be able to tell what Coconut code did without knowing what compiler flags it was intended to be compiled with. All `--strict` does is enable more errors and warnings. It doesn't change how your code actually functions.

My issue with extending shorthand function notation is that, reading the code, you would have no way of knowing whether a function returned the last expression or not without looking up to the top of the function and finding whether it was defined with an `=` or a `:`. For really long functions, that could lead to some nasty bugs. Shorthand function definition avoids this issue by only allowing a single expression.

**Comment by chuckwondo** [comment] 2016-08-10 22:04
@evhub Makes sense regarding the compiler flag, and now I understand what you mean regarding long functions using the shorthand function notation. I thought you were referring to difficulty with implementing it in the compiler, but you mean that the person writing the code might run into difficulties. Thanks again for the clarification.

**Comment by chuckwondo** [comment] 2016-08-12 19:20
@evhub In light of something I recently discovered in Scala, I'd like you to reconsider a possible solution for this. I know this is a long message, but please bear with me :-)

Scala supports 2 different function notations. One with an `=` sign and one without (know as the procedure syntax, I believe). When using an `=` sign (similar to Coconut's shorthand function notation, but supporting multiple lines), Scala automatically returns the value of the last expression in the function, without requiring use of the `return` keyword. Again, just like Coconut's shorthand function notation.

The procedural syntax simply drops the `=` sign and implies a return type of `Unit`, which indicates the function acts like a procedure (i.e., does _not_ return a value, sort of), which is roughly equivalent to a `void` return type in Java. This is also roughly how Python behaves when a function does not use a `return` statement (it simply returns `None`, as you mentioned earlier).

To continue supporting Python 3 as valid Coconut code, what if you continue to use the standard function syntax (with a `:`), where you make no assumptions about whether or not the function is behaving like a procedure (i.e., whether or not it explicitly returns a value using a `return` statement), but expand the shorthand function syntax (using `=` in place of `:`) to support multiple lines, and when there are multiple lines, automatically insert the `return` keyword at the beginning of the last line?

I know you said you don't want to force developers to have to look up to the top of their function to see whether there's a `:` or an `=`, but I suggest that it's not something that would be problematic, particularly given that this is essentially what Scala does.

As a counterpoint, I believe the latest stable version (2.11?) of Scala has deprecated the procedure syntax (primarily to avoid confusion amongst Scala beginners). However, I don't suggest doing so in Coconut because that would mean deprecating Python 3 as valid Coconut because it would mean supporting _only_ the use of `=`.

I have some further points to attempt to sway you on this:

1. The Scala compiler has a flag that you can use to have the compiler emit warnings (see Value Discarding section in [Useful Scala Compiler Options for Better Scala Development](https://dzone.com/articles/useful-scala-compiler-options-for-better-scala-dev)), which may be something you could closely model with the Coconut compiler.

    The warnings are for _value discarding_. That is, when using the procedural syntax, but having an expression as the last line of a function. The warning alerts you to the fact that no value will be returned even though it looks like you intended for the value of that last expression to be returned, and that you perhaps intended to use an `=` at the top of your function.

    However, in Coconut there may be a need for 2 types of warnings that could be enabled:

    1. Warnings when a standard Python function (with a `:`) does _not_ explicitly return the value of the final expression.
    1. Warnings when the Coconut function (with an `=`) _does_ explicitly return the value of the final expression, which is unnecessary.

1. If a developer has to scroll to see the top of the function they're currently coding (in order to see whether there's a `:` or an `=`), then I'd say their function is likely much longer than it should be, and thus they may run into all sorts of other trouble anyway.
1. If you're coding in Coconut, I'm guessing it's primarily because of the great FP conventions, and thus, you may be used to other FP languages where implicitly returning the value of the last evaluated expression is the norm, so you're generally not going to be surprised by this. Thus, you would normally use the `=` in Coconut (particularly as programming in Coconut becomes more natural to you) rather than the `:`, assuming the `=` notation is extended to support multiple lines.
1. Finally, since the shorthand notation already drops the use of the `return` keyword, it appears as though extending the shorthand notation to full-on notation won't cause any backward compatibility issues. That is, Python 3 syntax would still be valid Coconut, and shorthand notation would still work as well, so extending the notation to support multiple lines should work without issue (unless of course I'm still missing something).

Sorry that was so long, but if you're willing to consider this, I would be happy to attempt this change and submit a PR for it to see if you like it. (Of course, I'm sure I'll have to ask for your guidance.)

**Comment by evhub** [comment] 2016-08-12 20:37
@chuckwondo I think that's a reasonable argument. I'll re-open this issue, with the idea of implementing an extension of shorthand function notation to support multiple lines.

**Comment by chuckwondo** [comment] 2016-08-13 22:20
Excellent. I'm happy to take a stab at this, if you would point me in the right direction as to where to look in the code.

**Comment by evhub** [comment] 2016-08-15 16:33
@chuckwondo The change will be to `math_funcdef` in `compiler.py`. But I can take care of that. What would really be helpful, actually, is if you can add some tests to [`cocotest`](https://github.com/evhub/cocotest).

**Comment by chuckwondo** [comment] 2016-08-15 22:40
@evhub Sure thing. Just point me in the right direction as to where I might do so.

**Comment by evhub** [comment] 2016-08-15 22:58
@chuckwondo Sure thing! The basic idea of that repository is that it is a bunch of Coconut code that uses every single Coconut feature to make sure that they all work. There are only three files there that you'll really care about:

- `src/cocotest/main.coco`: All the tests that don't depend on any definitions to make them work (otherwise they would be in `util.coco` and `suite.coc`).
- `src/cocotest/util.coco`: Lots of function, class, and data definitions. Tested in `suite.coc`.
- `src/cocotest/suite.coc`: The actual tests for everything defined in `util.coco`. The `.coc` instead of `.coco` is intentional to test that both extensions work.

But really, that repository isn't all that well organized. So it doesn't really matter where you put the tests, as long as they're in one of the files above.

**Comment by evhub** [comment] 2016-08-23 00:58
@chuckwondo This is now live in develop.

**Closed by evhub** 2016-08-23 00:58 UTC
Labels: feature

**Comment by chuckwondo** [comment] 2016-08-23 23:37
@evhub Thanks so much! I was trying to determine how/where to add tests for this, and as I was trying to understand cocotest, I finally stumbled upon the test that you've already added. Now that I have an example, I'll try adding another one. Thanks again.

**Comment by evhub** [comment] 2016-08-23 23:44
@chuckwondo The test I added was pretty minimal, so you're welcome to add more. And sorry about how messy the test infrastructure is! Cleaning it up (ideally by moving everything in `cocotest` into the main repository and changing `coconut-travis-generator` to reflect that) is something I've been meaning to do for a while but haven't had the time to get around to. I think I'll create a ticket for that.

**Comment by Nexus6** [comment] 2016-10-07 03:58
Thanks guys, this made my day!  Coming from Scala-land I detest the 'return' statement of Python.  I'm delighted that coconut now gives me a way to avoid it, and the approach used here is very clean syntax-wise.

**Comment by evhub** [comment] 2016-10-07 05:07
@Nexus6 Thanks! I'm glad you're enjoying using Coconut. If you have any comments/suggestions/questions/etc., feel free to open an issue or stop by Coconut's [Gitter](https://gitter.im/evhub/coconut)!
