### ISSUE TITLE
CoconutInternalException: out of bounds line number: 12 (not in range [1, 11])

### ISSUE THREAD

**Issue by poglesbyg** [evhub/coconut#462] opened 2018-11-13 12:32 UTC
`def fact5(n, acc=1):
    """Compute n! where n is an integer >= 0."""
    case n:
        match 0:
            return acc
        match _ is int if n > 0:
            return fact5(n-1, acc*n)
    else:
        raise TypeError("the argument to factorial must be an integer >= 0")
            `
This is the code that I put into jupyter lab, however in jupyter I ran it with an empty line at the bottom by accident. It runs without the last empty line at the bottom. However, when I run the code with the line, it gives me this error:

> CoconutInternalException: out of bounds line number: 12 (not in range [1, 11]) (you should report this at https://github.com/evhub/coconut/issues/new)
CoconutInternalException: out of bounds line number: 12 (not in range [1, 11]) (you should report this at https://github.com/evhub/coconut/issues/new)

**Comment by evhub** [comment] 2018-11-13 21:45
@poglesbyg As a temporary fix, try disabling (not passing) `--keep-lines`.

**Comment by evhub** [comment] 2019-03-03 10:50
@poglesbyg This should be fixed on `coconut-develop`! Just `pip install -U coconut-develop` to get the latest version.

**Comment by evhub** [comment] 2019-03-03 10:51
(also marking this a duplicate of #391)

**Closed by evhub** 2019-03-03 10:50 UTC
Labels: bug, resolved
