### ISSUE TITLE
Assignment functions enhancement

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#316] opened 2017-09-06 05:44 UTC
The syntax for [assignment functions](http://coconut.readthedocs.io/en/master/DOCS.html#assignment-functions) is rather strict: You either have a one-line definition plus expression a lot like a lambda), or a block with statements and a trailing expression.

But having
```
def func(x) =
  a = 2 * compute(x)
  assert a >= 0.
  a  # implicitly returns a
```
is not better than
```
def func(x):
  a = 2 * compute(x)
  assert a >= 0.
  return a
```
yet
```
def func(x) = 2 * compute(x)  # leaving out the assert statement makes the code easier to be written as an assignment function
```
is, but in real life code can use several local variables and loops that don't allow this kind of simplification.
Omitting the return statement makes the code not more beautiful, but looks rather wrong for the casual Python programmer.

Allowing assignments, however, to be evaluated as a valid expression and implicit return value would allow some real enhancements and code reduction:
```
def func(lizt):
  acc = 0.
  for elem in lizt:
    value = compute(elem)
    assert value >= 0.
    acc += value
```
which implicitly returns acc, as it is the last evaluated expression (assignment should be an expression in this position).
What do you think?

**Comment by evhub** [comment] 2017-09-06 06:12
@ArneBachmann Thanks for the detailed bug report! Your proposal is slightly different from the one in #190, but the issues are similar enough that I'm going to close this as a duplicate of #190 . Also, if I implement this, I'll probably go with the implementation currently detailed in #190 instead of the one here, since I dislike the idea of an implicit return being hidden inside of a function instead of clearly the last expression.

**Closed by evhub** 2017-09-06 06:12 UTC
