### ISSUE TITLE
Add implicit partial for multiple indexing

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#231] opened 2017-03-04 03:51 UTC
I am trying to run this:

```coconut
        return (
            inputs.s
            |> tf.layers.dense$(?, 32, activation=tf.nn.relu, name='relu_layer', **ops)
            |> tf.nn.dropout$(?, inputs.keep_prob)
            |> tf.layers.dense$(?, 1, name='linear_layer', **ops)
            |> .[:, 0]
        )
```
but I am getting
> CoconutParseError: parsing failed (line 147)

This other form is not working either
```coconut
        return (
            inputs.s
            |> tf.layers.dense$(?, 32, activation=tf.nn.relu, name='relu_layer', **ops)
            |> tf.nn.dropout$(?, inputs.keep_prob)
            |> tf.layers.dense$(?, 1, name='linear_layer', **ops)
            |> lambda t: t[:, 0]
        )
```
I had to wrap the lambda inside parenthesis for the compiler to work properly:
```coconut
        return (
            inputs.s
            |> tf.layers.dense$(?, 32, activation=tf.nn.relu, name='relu_layer', **ops)
            |> tf.nn.dropout$(?, inputs.keep_prob)
            |> tf.layers.dense$(?, 1, name='linear_layer', **ops)
            |> (lambda t: t[:, 0])
        )
```

**Comment by evhub** [comment] 2017-03-04 20:19
@cgarciae The problem is that `.[:, 0]` is not a valid implicit partial, since as currently implemented it doesn't support comma syntax. That's definitely something worth implementing, though. Another workaround until then is `(-> _[:, 0])` using implicit lambda syntax.

**Comment by evhub** [comment] 2017-03-22 01:09
@cgarciae Fixed on `coconut-develop`! Just `pip install coconut-develop` to get the new behaviour.

**Closed by evhub** 2017-03-22 01:09 UTC
Labels: enhancement, resolved

**Comment by cgarciae** [comment] 2017-03-23 16:16
Thanks!
