### ISSUE TITLE
Some Unicode characters are replaced with a newline

### ISSUE THREAD

**Issue by dokutan** [evhub/coconut#825] opened 2024-01-23 16:30 UTC
When coconut encounters a string literal containing either an unescaped paragraph separator (U+2029) or a line separator (U+2028), these characters are replaced by a newline. There could be other codepoints with this problem, as i haven't tested many. I have tested this behaviour with python 3.11 and coconut 3.0.4 on python 3.11.
Additionally this causes a ` CoconutSyntaxError: linebreak in non-multi-line string` if the string is not a multi-line string.

To reproduce:
```sh
printf "print('''\u2029'''=='''\n''')" | coconut   # True
printf "print('''\u2029'''=='''\n''')" | python    # False
```

**Comment by evhub** [comment] 2024-01-23 23:26
Duplicate of #818—this should be fixed as of `coconut-develop>=3.0.4-post_dev14` (`pip install -U coconut-develop>=3.0.4-post_dev14` to get the fix).

**Closed by evhub** 2024-01-23 23:26 UTC
Labels: duplicate, oversight, resolved
