### ISSUE TITLE
Define unicode operators

### ISSUE THREAD

**Issue by zhichu** [evhub/coconut#651] opened 2022-03-03 03:00 UTC
The unicode alternatives of the operators are brilliant. But is there any way that I can define my own one?

For example, I'm writing a function that checks whether a variable is an element of a set, which is either a finite one (a list, e.g., `⟦1,3,5,7,9⟧`), or a range over an ordered field (e.g., `⟦1…100, ℝ⟧`). I can define the infix function `` `elemOf` `` (with back-ticks), but can I make an alias to the unicode symbols: `∈`, `∉` (without back-ticks), etc.?

Also, is it possible to map a `data` constructor to a unicode symbol set? Like use `⟦...⟧` as an alternative to the `set(...)` constructor.

Maybe this is a very stupid question, but can anyone point out some other references to solving my problem? I am a `haskell` guy and I'm really new in `coconut` and `python`.

**Comment by evhub** [comment] 2022-03-03 07:54
Duplicate of #4.

**Comment by evhub** [comment] 2022-03-03 23:29
Sorry, #4 is a very old issue and I don't think it's very clear what it's proposing (in fact I think it might predate the addition of infix functions). #4 is about adding syntax for defining custom Unicode operators, it just proposes to use the same syntax as for defining infix functions.

I am definitely interested in adding this functionality at some point, though it's a pretty big feature and also does have some drawbacks—e.g. making it harder to use Coconut code from Python code and requiring Unicode editor shortcuts to type Coconut—that will need to be worked around.

**Comment by zhichu** [comment] 2022-03-04 02:12
I see. Good to know it's interesting to you.

Anyway, thanks for creating `Coconut`. I really like it.

**Comment by evhub** [comment] 2022-03-04 02:13
Thanks; glad to hear it!

**Comment by evhub** [comment] 2022-10-04 05:17
This is now live on `coconut-develop>=2.0.0-post_dev4`! Check out [the `develop` documentation](https://coconut.readthedocs.io/en/develop/DOCS.html#custom-operators) for more info.

**Closed by evhub** 2022-10-04 05:17 UTC
Labels: duplicate, feature
