### ISSUE TITLE
Ipython and Jupyter `unexpected keyword argument cell_id`

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#657] opened 2022-04-18 16:47 UTC
May be a repeat of #551, but I'm running `coconut-develop2.0.0a0.dev51[kernel]` and this just started happening. Trying to run cells with a dedicated coconut kernel now causes a "Timeout waiting for kernel_info reply", even though running cells within python and the `%load_ext coconut` enabled works just fine in a `%%coconut` cell. 

The changelog for Ipython 8.0-2 is [here](https://ipython.readthedocs.io/en/stable/whatsnew/version8.html), but I don't see any specific `cell_id` references. Perhaps it has to do with the removal of deprecated functions? 

Here's the full traceback in the jupyter notebook log:
 
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/tbsexton/miniconda3/envs/text-data/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/home/tbsexton/miniconda3/envs/text-data/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 724, in execute_request
    reply_content = await reply_content
  File "/home/tbsexton/miniconda3/envs/text-data/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "<string>", line 21, in run_cell
  File "/home/tbsexton/miniconda3/envs/text-data/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
TypeError: run_cell() got an unexpected keyword argument 'cell_id'
[W 12:21:35.851 NotebookApp] Timeout waiting for kernel_info reply from 3549ce30-58eb-4d86-b0d6-bf078ee225d2
[E 12:21:35.852 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 3549ce30-58eb-4d86-b0d6-bf078ee225d2)

```

FWIW The code is [here](https://tlp-coi.github.io/text-data-course/appendix/tutorials/markovian-shakespeare.html), which was working fine I'd say... 2 months ago-ish? 

NB. I will say that devs like you have put so much work into getting the kernel stuff working, and I'm getting a little tired of you all having to deal with the `nb_conda_kernels` situation. It breaks so often! But I can't find another alternative for not running 500 separate jupyter servers for every project environment I need.  :P

**Comment by evhub** [comment] 2022-04-22 20:29
Thanks for the bug report! This should be fixed now on `coconut-develop>=2.0.0-a_dev52`.

The issue isn't with `nb_conda_kernels`—it's that `ipykernel` added a new `run_cell` argument and uses some really hacky function signature inspection to figure out whether to pass it in that yields a false positive for Coconut's implementation.

**Closed by evhub** 2022-04-22 20:29 UTC
Labels: bug, resolved
